import FileSystem from 'expo-file-system';
import { STORAGE_DIRECTORY_URI } from './contants';

/**
 * Creates the directory used by the FileSystem to store all information
 * generated by this application
 */
export async function createDirectory() {
  const { exists } = await FileSystem.getInfoAsync(STORAGE_DIRECTORY_URI);

  // early-termination if the storage directory already exists
  if (exists) return;

  FileSystem.makeDirectoryAsync(STORAGE_DIRECTORY_URI, { intermediates: true });
}
